version: '3.8'
services:
  openpose:
    image: your_openpose_image_name # 替换为你的镜像名
    container_name: openpose_camera
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /dev/video0:/dev/video0 # 将主机摄像头设备挂载到容器
    devices:
      - /dev/video0:/dev/video0 # 提供设备访问权限
    environment:
      - DISPLAY=${DISPLAY} # 显示环境变量（如需要在容器内渲染）
      - QT_X11_NO_MITSHM=1
    network_mode: "host" # 如果需要使用主机的网络堆栈
    ipc: host # 共享主机的进程间通信机制
    privileged: true # 允许容器访问硬件
